// All renderer-visible bridge language lives here so a status value can never
// become UI text accidentally.  Keep this free of codes, secrets and emoji.
export const BRIDGE_COPY = Object.freeze({
  health: Object.freeze({
    off: ['Bridge off', 'Turn on the bridge when you are ready.'],
    setup: ['Setup needed', 'Finish the required setup steps before ChatGPT can help.'],
    alarm: ['Paused: unexpected caller', 'Calls with a valid ChatGPT link but the wrong chat code were refused. If this was not you, revoke access.'],
    fault: ['Bridge needs attention', 'The bridge stopped serving until you address this problem.'],
    paused: ['Paused', 'ChatGPT is told to wait and nothing is served. The tunnel and the link stay up.'],
    restart: ['Confirm to restart', 'The bridge restarted, so every earlier ChatGPT chat has ended. Press Start a new chat to confirm the released jobs and begin again.'],
    'tunnel-problem': ['Tunnel needs attention', 'ChatGPT cannot reach this Mac until the tunnel is ready.'],
    starting: ['Starting tunnel', 'Connecting this Mac to ChatGPT.'],
    'tunnel-unreachable': ['Tunnel unreachable', 'ChatGPT cannot reach this Mac right now.'],
    'link-problem': ['ChatGPT link needs renewing', 'First press Open pairing here, then press Reconnect in ChatGPT and type the code on the page your browser opens.'],
    'needs-you': ['Needs you', 'One or more jobs need your attention in the dock.'],
    'duplicate-serve': ['Two chats are using one code', 'Start a fresh chat so only one chat is serving this work.'],
    stalled: ['ChatGPT has been quiet', 'It may still be writing, may have been blocked, or the chat may have been closed.'],
    'chat-full': ['Start a new chat', 'This chat has reached its work limit.'],
    working: ['ChatGPT is working', 'A handoff is currently with ChatGPT.'],
    saving: ['The app is saving this', 'The app is applying a finished answer.'],
    'first-call': ['Waiting for chat', 'Check the plugin appeared as a chip and the message was sent.'],
    nudge: ['Waiting for ChatGPT', 'Start a new chat, or paste Continue into the existing chat.'],
    'chat-idle': ['Chat is idle', 'Nothing is waiting right now.'],
    ready: ['Ready', 'Linked and reachable. Nothing is waiting.'],
  }),
  hygiene: Object.freeze([
    'Use a dedicated ChatGPT Project with memory, web browsing, and connected apps turned off. Delete each chat afterward.',
    'The copied starter contains this chat\'s code. It remains on the system clipboard for up to two minutes and may also be captured by clipboard managers or Universal Clipboard; clear it there too.',
    'Review each finished resume and cover letter before sending it. Even an answer that passes every check may have been steered by a job listing.',
  ]),
  dockNote: 'The copy/paste dock keeps working. If you paste an answer for a job ChatGPT is handling, the bridge stops serving that job. Do not type into a chip ChatGPT is driving.',
  keepAwakeOn: 'During bridge work, the app asks macOS to stay awake and keeps this window\'s timers running. Closing the lid still sleeps your Mac.',
  keepAwakeOff: 'During bridge work, your Mac may sleep or slow this window\'s timers. The bridge may respond slowly—or not at all—until it wakes. Closing the lid always sleeps your Mac.',
  e2eUnavailable: 'The bridge is disabled during automated test runs.',
  noWindow: 'Open a canvas window first.',
});

export const BRIDGE_ACTION_COPY = Object.freeze({
  enable: 'Turn on',
  setup: 'Open setup',
  'open-panel': 'Open panel',
  'revoke-all': 'Revoke access',
  resume: 'Resume',
  'new-chat': 'Start a new chat',
  'restart-tunnel': 'Restart tunnel',
  'open-pairing': 'Open pairing',
  'open-dock': 'Open in dock',
  'copy-starter': 'Copy starter',
});

export const BRIDGE_DYNAMIC_COPY = Object.freeze({
  setup: next => ['Setup needed', `Next: ${next}`],
  alarm: amount => ['Paused: unexpected caller', `Calls with a valid ChatGPT link but the wrong chat code were refused ${amount} ${amount === 1 ? 'time' : 'times'}, so the bridge paused itself. If this was not you, revoke access.`],
  // Fault identifiers are deliberately not rendered.  A future main-process
  // value must not become renderer-visible diagnostic text.
  fault: () => ['Bridge error', 'The bridge stopped itself after an internal error. Turn it off and on again. If it repeats, copy a bug report.'],
  idlePaused: hours => [`Paused: nothing from you for ${hours} h`, 'Nothing has been served since you last acted here. Press Resume to continue.'],
  quitPaused: () => ['Closing', 'Nothing more is served while the app closes.'],
  tunnelFailures: failures => ['Tunnel unreachable', `${failures} checks in a row failed; ChatGPT cannot reach this Mac right now.`],
  linkRenewal: () => ['ChatGPT link needs renewing', 'ChatGPT can no longer use its link to this app. First press Open pairing here, then press Reconnect in ChatGPT and type the code on the page your browser opens.'],
  linkExpiresSoon: () => ['ChatGPT link expires soon', 'You can renew it any time: open pairing, then press Reconnect in ChatGPT.'],
  toolsStale: () => ['Refresh the plugin in ChatGPT', 'This app version changed the tool descriptions since ChatGPT last read them. In ChatGPT open the plugin settings and press Refresh.'],
  needsYou: amount => [`Needs you (${amount})`, BRIDGE_COPY.health['needs-you'][1]],
  stalled: (age, work) => [`ChatGPT has been quiet for ${age} min`, `ChatGPT was given ${work} ${age} min ago and has not sent an answer since. It may still be writing, may have been blocked, or the chat may have been closed. If ChatGPT says a tool call was blocked or is no longer available, start a fresh chat: answers already accepted are kept and the new chat resumes at the step that was waiting.`],
  firstCall: ordinal => [`Waiting for chat ${ordinal || ''}`.trim(), BRIDGE_COPY.health['first-call'][1]],
  nudge: (amount, ordinal) => [`${amount} waiting for ChatGPT`, ordinal ? `Chat ${ordinal} has stopped. Paste Continue into it, or start a new chat.` : 'Start a chat to hand them over.'],
  chatIdle: (ordinal, lastCall) => [`Chat ${ordinal || ''}: idle`.trim(), `Last call ${lastCall}. Nothing is waiting.`],
});

export const RELATIVE_TIME_COPY = Object.freeze({
  never: 'never',
  now: 'just now',
  minutes: value => `${value} min ago`,
  hours: value => `${value} h ago`,
  days: value => `${value} d ago`,
});

export const JOB_ROW_COPY = Object.freeze({
  awaiting: 'Waiting for ChatGPT',
  withChat: ordinal => `With ChatGPT (chat ${ordinal})`,
  host: 'The app is saving this',
  done: 'Saved',
  gone: 'Discarded',
  held: 'Kept for you',
  answered_in_dock: 'Answered here; ChatGPT stopped serving it',
  integrity_fault: 'Needs you: this job cannot continue. See the dock.',
  failed: 'Needs you: this job failed. See the dock.',
  render_retry_required: 'Needs you: press Retry layout check on the job card.',
  rejection_cap: 'Needs you: ChatGPT\'s answers were rejected too many times.',
  review_round_cap: 'Needs you: too many review rounds.',
  junk_cap: 'Needs you: ChatGPT sent empty answers repeatedly.',
  host_silent: 'Needs you: the app has not moved this job for 10 minutes. Is its canvas open?',
  job_broken: 'Needs you: this job cannot continue. See the dock.',
  render_retry: 'Needs you: press Retry layout check on the job card.',
  canvas_unavailable: 'Needs you: this canvas is not available. Open it, then see the dock.',
  read_failed: 'Needs you: this job could not be read. See the dock.',
  write_failed: 'Needs you: the app could not save this answer. See the dock.',
  submit_stuck: 'Needs you: the app has not finished saving this answer. See the dock.',
  lapsed: 'Needs you: this job is no longer released. See the dock.',
  restart: 'Needs you: confirm the restart before serving this job. See the dock.',
  app_only_handoffs: 'Needs you: this job stays in the copy/paste dock. See the dock.',
  user_hold: 'Kept for you',
  human_advance: 'Answered here; ChatGPT stopped serving it',
  commit_failed: 'Needs you: the app could not finish this change. See the dock.',
  person_editing: 'Kept for you',
  hub_not_selected: 'Needs you: select this scoring handoff before serving it. See the dock.',
  task_disabled: 'Needs you: this scoring handoff is not enabled. See the dock.',
  unreadable: 'Reading this job failed; retrying',
});

export const ACTIVITY_COPY = Object.freeze({
  'link-paired': 'ChatGPT linked',
  'link-revoked': 'Link revoked',
  'link-refresh-failed': 'ChatGPT\'s link could not be renewed',
  'chat-started': 'Chat started',
  'chat-continued': 'Continue message copied',
  'get-served': 'Handed over a handoff',
  'get-waiting': 'Told ChatGPT to wait',
  'get-empty': 'Told ChatGPT nothing is waiting',
  'submit-accepted': 'Accepted an answer',
  'submit-rejected': 'Rejected an answer; ChatGPT was sent the fixes',
  'submit-duplicate': 'Ignored a repeated answer',
  'submit-junk': 'Ignored an empty answer',
  'submit-superseded': 'An answer arrived after the step had moved on',
  'submit-held': 'Answer not applied (job kept for you)',
  stall: 'No answer from ChatGPT',
  paused: 'Paused',
  resumed: 'Resumed',
  'tunnel-up': 'Tunnel connected',
  'tunnel-down': 'Tunnel unreachable',
  'tunnel-restart': 'Tunnel restarted',
  alarm: 'Unexpected caller',
  enabled: 'Turned on',
  disabled: 'Turned off',
  unknown: 'Bridge event',
});

export const BRIDGE_UI_COPY = Object.freeze({
  done: 'Done.',
  saved: 'Saved.',
  copied: 'Copied.',
  panelLabel: 'ChatGPT bridge',
  settingsLabel: 'ChatGPT bridge settings',
  closePanel: 'Close bridge panel',
  pause: 'Pause',
  resume: 'Resume',
  chat: 'Chat',
  noChat: 'No chat started',
  workingOn: value => `Working on ${value}`,
  application: 'Application',
  recently: 'recently',
  chatOrdinal: value => `Chat ${value}`,
  copyContinue: 'Copy Continue',
  startChat: 'Start a new chat',
  applications: 'Applications',
  sendAll: 'Send all pending',
  release: 'Release',
  readyToRelease: 'Ready to release',
  keepForMe: 'Keep for me',
  resumeServing: 'Resume serving',
  openDock: 'Open in dock',
  otherWindows: value => `and ${value} in other windows`,
  scoring: 'Scoring and research',
  scoringHub: (ordinal, pending) => `Scoring handoff ${ordinal} (${pending} waiting)`,
  scoringSummary: (pending, withChat) => `${pending} waiting, ${withChat} with ChatGPT`,
  activity: 'Activity',
  noActivity: 'No bridge activity yet.',
  counts: 'Counts since launch',
  served: 'Served',
  accepted: 'Accepted',
  rejected: 'Rejected',
  duplicates: 'Duplicates',
  junk: 'Junk',
  stalls: 'Stalls',
  tunnelRestarts: 'Tunnel restarts',
  also: 'Also:',
  revoke: 'Revoke ChatGPT access…',
  turnOff: 'Turn off',
  confirmNewTitle: 'Start a new chat?',
  confirmNewMessage: (ordinal, age) => `Chat ${ordinal} last called ${age}. Starting a new chat stops it: its next call is refused, and the new chat picks up where it left off.`,
  confirmNew: 'Start new chat',
  keepChat: ordinal => `Keep chat ${ordinal}`,
  confirmOffTitle: 'Turn off the bridge now?',
  confirmOffMessage: 'ChatGPT has an unanswered handoff. Turning off ends that step; nothing already accepted is lost.',
  keepOn: 'Keep it on',
  confirmRevokeTitle: 'Revoke ChatGPT access?',
  confirmRevokeMessage: 'This disconnects the current ChatGPT link and ends the active chat. Released jobs remain in this app.',
  confirmRevoke: 'Revoke access',
  settingsHeading: 'ChatGPT bridge',
  settingsGroup: 'ChatGPT bridge controls',
  enabledLabel: 'Turn on the ChatGPT bridge',
  checkingAvailability: 'Checking bridge availability…',
  retryAvailability: 'Try again',
  unavailable: 'The bridge is unavailable in this build.',
  envDisabled: 'The bridge was disabled by this app launch.',
  setUp: 'Set up…',
  manage: 'Manage…',
  openPanel: 'Open panel',
  scoringSetting: 'Let ChatGPT handle scoring handoffs',
  autoStart: 'Turn on when the app starts',
  autoRelease: 'Automatically release new application handoffs this session',
  dangerZone: 'Danger zone',
  forget: 'Forget setup…',
  confirmForgetTitle: 'Forget bridge setup?',
  confirmForgetMessage: 'This turns off the bridge, revokes its ChatGPT link and clears this app’s bridge settings. It does not delete the Cloudflare tunnel or the plugin in ChatGPT.',
  confirmForget: 'Forget setup',
  confirmAddressTitle: 'Change the public address?',
  confirmAddressMessage: 'Changing the public address breaks the current ChatGPT link. You will need to create or reconnect the plugin at the new address.',
  confirmAddress: 'Change address',
  keepAddress: 'Keep current address',
  cancel: 'Cancel',
  triggerLabel: headline => `ChatGPT bridge: ${headline}`,
  externalLinkFailure: 'Could not open the ChatGPT plugin settings. Please try again.',
});

// cloudflared can put addresses, local paths and credential-shaped values in a
// diagnostic.  The log is optional UI troubleshooting, never a transport for
// raw process output.  Keep just a bounded, redacted single line.
export function sanitizeTunnelLogLine(value) {
  if (typeof value !== 'string') return null;
  const redacted = [...value].map(character => {
    const code = character.codePointAt(0);
    return code <= 31 || (code >= 127 && code <= 159) ? ' ' : character;
  }).join('')
    .replace(/https?:\/\/\S+/gi, '<url>')
    .replace(/(?:\/[^\s'"\\]+)+/g, '<path>')
    .replace(/\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/gi, '<tunnel-id>')
    .replace(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g, '<address>')
    .replace(/\b(token|secret|credential|authorization|bearer|password)\s*[=:]\s*[^\s]+/gi, '$1=<redacted>')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 200);
  return redacted || null;
}

export const BRIDGE_SETUP_COPY = Object.freeze({
  title: 'Set up ChatGPT bridge',
  close: 'Close setup',
  steps: Object.freeze(['Overview', 'Tunnel', 'Plugin and link', 'First chat']),
  goTo: step => `Go to ${step}`,
  back: 'Back',
  next: 'Next',
  finish: 'Done',
  overview: 'Send released application and scoring handoffs to a ChatGPT plugin through a Cloudflare tunnel approved on this Mac.',
  requirements: 'You need cloudflared; a named Cloudflare tunnel and its credentials file; a public address in your zone; and a dedicated ChatGPT Project.',
  tunnelLead: 'Choose and approve cloudflared, then choose the credentials file for the named tunnel.',
  chooseBinary: 'Choose cloudflared…',
  approveBinary: 'Approve cloudflared…',
  chooseCredentials: 'Choose credentials…',
  publicAddress: 'Public address',
  hostnamePlaceholder: 'bridge.your-domain.com',
  pluginName: 'Plugin name',
  saveAddress: 'Save address',
  restartTunnel: 'Restart tunnel',
  showLog: 'Show tunnel log',
  tunnelLog: 'Recent tunnel diagnostics',
  noTunnelLog: 'No tunnel diagnostics are available yet.',
  noTunnel: 'Don’t have a tunnel yet?',
  tunnelCommands: 'Log in and create a named tunnel in Terminal. Copy the UUID printed by create and use it to route the hostname. Do not route by name: a default config can select the wrong tunnel. Return here and choose the new credentials JSON. The app builds ingress; do not run a token command.',
  tunnelCommandList: Object.freeze(['cloudflared tunnel login', 'cloudflared tunnel create NAME', 'cloudflared tunnel route dns <UUID_FROM_CREATE_OUTPUT> bridge.your-domain.com', 'cloudflared tunnel list']),
  zoneChecklist: 'In Cloudflare, make sure the public hostname is in your zone and routes to this named tunnel.',
  binary: 'Tunnel program',
  credentials: 'Credentials file',
  approved: 'Approved',
  notApproved: 'Needs approval',
  noBinary: 'Not selected',
  binarySelected: 'Selected',
  noCredentials: 'Not selected',
  credentialsSelected: 'Selected',
  credentialsTooOpen: 'This credentials file is readable by other accounts. Restrict its permissions before continuing.',
  certPresent: 'A cert.pem file is present. This bridge uses the named-tunnel credentials file instead.',
  advanced: 'Advanced',
  status: 'Tunnel status',
  tunnelStates: Object.freeze({ off: 'Off', blocked: 'Blocked', 'needs-setup': 'Setup needed', 'needs-trust': 'Needs approval', starting: 'Starting', connecting: 'Connecting', 'checking-public': 'Checking public address', up: 'Online', degraded: 'Degraded', backoff: 'Waiting to retry', paused: 'Paused', stopping: 'Stopping', failed: 'Failed', unknown: 'Unknown' }),
  defaultPluginName: 'Infinite Canvas',
  commandPreview: 'The app runs the approved tunnel program with private configuration. This preview is not a command to copy.',
  pairingLead: 'Open pairing here before creating or reconnecting the plugin in ChatGPT.',
  openPairing: 'Open pairing',
  cancelPairing: 'Cancel pairing',
  openChatGpt: 'Open ChatGPT plugin settings',
  copyServerUrl: 'Copy server URL',
  progress: 'Link progress',
  progressItems: Object.freeze(['Plugin discovery opened', 'Permission requested', 'Pairing approved', 'Link issued', 'Tools listed']),
  pluginSteps: Object.freeze([
    'Open the ChatGPT web app, choose Apps, then create an MCP app.',
    'Use the plugin name and server address shown here, and choose OAuth authentication.',
    'Leave all Advanced OAuth fields blank. Before creating or reconnecting, press Open pairing here.',
    'Finish the browser pairing and choose Always allow the first time ChatGPT asks.',
  ]),
  serverUnavailable: 'Server address appears after tunnel setup.',
  earlyBlock: 'A brand-new plugin can be blocked for its first few minutes. If the first call is blocked, wait a few minutes and start a fresh chat.',
  reconnect: 'If ChatGPT shows Reconnect, open pairing here first, then press Reconnect and enter the code shown by this app.',
  firstChat: 'Start a new chat. Type @ and choose the plugin so it appears as a chip. Paste and send the starter, then leave the chat alone while it drains the queue.',
  chooseAndApproveBinaryFirst: 'Choose and approve cloudflared before continuing.',
  approveBinaryFirst: 'Approve cloudflared before continuing.',
  chooseCredentialsFirst: 'Choose the credentials file before continuing.',
  saveAddressFirst: 'Save the public address before continuing.',
  turnOnBridge: 'Turn on bridge',
  turningOnBridge: 'Turning on bridge…',
  turnOnBridgeFirst: 'Tunnel setup is saved. Turn on the bridge to start the tunnel.',
  waitForTunnel: 'The bridge is starting. Wait for the tunnel to be online before continuing.',
  completeLinkFirst: 'Link ChatGPT before starting a chat.',
  bridgeMustBeReady: 'Turn on the bridge and finish setup before starting a chat.',
  invalid: 'That value is not valid.',
});

export const IPC_ERROR_COPY = Object.freeze({
  UNAVAILABLE: 'The bridge is not available in this build.', SENDER: 'That action is not allowed from this window.', BUSY: 'Another bridge dialog is open. Finish it first.', DECLINED: 'Cancelled.', INVALID: 'That value is not valid.', NO_WINDOW: 'Open a canvas window first.', NOT_READY: 'Finish setup first.', TUNNEL_NOT_READY: 'The tunnel is not reachable yet.', NOT_LINKED: 'Link ChatGPT first.', PAUSED: 'The bridge is paused. Resume it first.', NO_CHAT: 'No chat has started yet. Use Start a new chat.', CLIPBOARD_FAILED: 'Could not copy to the clipboard. Try again.', NOT_FOUND: 'That item is no longer there.', LIMIT_REACHED: 'The bridge has reached its handoff limit.', UNKNOWN_JOB: 'That job is no longer available.', DISABLED: 'Turn on the bridge first.', LINK_WOULD_BREAK: 'Changing this breaks the ChatGPT link.', INTERNAL: 'Something went wrong in the bridge. Try again; if it repeats, copy a bug report.',
});
export function ipcErrorMessage(code) { return IPC_ERROR_COPY[code] || IPC_ERROR_COPY.INTERNAL; }
